---
include:
  - project: "papers/papers-internal/internal"
    file: "/.base-gitlab-ci.yml"

variables:
  NAMESPACE: "websocket-proxy"

.run_dev:
  extends: .before_script_dev
  only:
    - master
    - main
    - develop
    - dev


stages:
  - build
  - test
  - publish
  - deploy


build:
  stage: build
  extends: .build

test:
  stage: test
  script:
    - docker run $GOOGLE_TAG bash -c "yarn test:ci"


publish-dev:
  stage: publish
  extends: .publish-dev

publish-prod:
  stage: publish
  extends: .publish-prod


.deployment_script:
  script:
    # seds
    - find k8s -type f -name \*.yaml -exec sed -i "s|__NAMESPACE_NAME__|"$NAMESPACE"|g" {} +
    - find k8s -type f -name \*.yaml -exec sed -i "s|__TO_BE_REPLACED_BY_IMAGE_TAG__|"$IMAGE_TAG"|g" {} +

    # applying the files
    - kubectl apply -f k8s/common/namespace.yaml
    # - kubectl apply -f k8s/common/secret.yaml
    - kubectl apply -f k8s/$CI_ENVIRONMENT_NAME/ --recursive
    - kubectl apply -f k8s/common/ --recursive



k8s-deploy-development:
  stage: deploy
  extends: .run_dev
  when: manual
  needs: ["publish-dev"]
  variables:
    IMAGE_TAG: $GOOGLE_TAG_DEV
  script:
    - !reference [.deployment_script, script]
  environment: 
    name: development
    url: https://websocket-proxy.dev.gke.papers.tech


k8s-deploy-development-2:
  stage: deploy
  extends: .run_dev
  when: manual
  needs: ["publish-dev"]
  variables:
    IMAGE_TAG: $GOOGLE_TAG_DEV
    NAMESPACE: "websocket-proxy-2"
  script:
    - !reference [.deployment_script, script]
  environment: 
    name: development-2
    url: https://websocket-proxy-2.dev.gke.papers.tech

k8s-deploy-production:
  stage: deploy
  when: manual
  extends: .run_prod
  needs: ["publish-prod"]
  variables:
    IMAGE_TAG: $GOOGLE_TAG
  script:
    - !reference [.deployment_script, script]
  environment: 
    name: production
    url: https://websocket-proxy.prod.gke.papers.tech
