# copy config file
# run docker-compose.yml

# (document the ports to be opened)
---

- name: Clone websocketproxy repo
  tags:
    - skip_ansible_lint
    - initial
    - update
  ansible.builtin.git:
    # yamllint disable-line rule:line-length
    repo: 'https://gcp:{{ ws_proxy_token }}@gitlab.papers.tech/papers/acurast/websocket_proxy.git'
    dest: /root/websocket_proxy
    force: true
    version: "{{git_sha}}"

# - name: Build docker image
#   tags:
#     - initial
#     - update
#   community.docker.docker_image:
#     build:
#       path: /root/websocket_proxy
#     name: websocketproxy
#     tag: {{git_sha}}
#     push: false
#     source: build

- name: Create proxy folder
  tags:
    - initial
  ansible.builtin.file:
    path: /root/proxy
    mode: '0777'
    state: directory

- name: Copy config
  tags:
    - initial
    - update
  ansible.builtin.template:
    src: websocket-config.json
    dest: /root/proxy/websocket-config.json
    mode: '0777'

- name: Copy Docker-compose
  ansible.builtin.template:
    src: docker-compose.yml
    dest: /root/proxy/docker-compose.yml
    mode: '0777'

- name: Restart node (1)
  tags:
    - update
    - docker
  changed_when: true
  ansible.builtin.command:
    chdir: /root/proxy
    cmd: docker compose down

- name: Restart node (2)
  tags:
    - update
    - docker
  changed_when: true
  ansible.builtin.command:
    chdir: /root/proxy
    cmd: docker compose up -d --build --force-recreate
