---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: __NAMESPACE_NAME__
  namespace: __NAMESPACE_NAME__
spec:
  selector:
    matchLabels:
      app: __NAMESPACE_NAME__
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: __NAMESPACE_NAME__
    spec:
      containers:
        - image: __TO_BE_REPLACED_BY_IMAGE_TAG__
          imagePullPolicy: IfNotPresent
          name: __NAMESPACE_NAME__-backend
          # envFrom:
          #   - configMapRef:
          #       name: __NAMESPACE_NAME__-config-map
          #   - secretRef:
          #       name: __NAMESPACE_NAME__-secret
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            timeoutSeconds: 30
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            timeoutSeconds: 30
          resources:
            requests:
              cpu: '0.1'
              memory: 400Mi
            limits:
              cpu: '0.1'
              memory: 400Mi
      restartPolicy: Always
