---
apiVersion: v1
kind: Secret
metadata:
  name: __NAMESPACE_NAME____INSTANCE_SUFFIX__-secret
  namespace: __NAMESPACE_NAME__
type: Opaque
stringData:
  acurast.proxy.config.json: |
    {
      "instanceName": "__NAMESPACE_NAME____INSTANCE_SUFFIX__",
      "permissions": {
        "allowList": [],
        "denyList": []
      },
      "bootstrap": {
        "peers": [ "__BOOTSTRAP_PEER__" ]
      },
      "peerId": {
        "id": "__PEER_ID__",
        "privKey": "__PEER_PRIVATE_KEY__",
        "pubKey": "__PEER_PUBLIC_KEY__"
      },
      "scheduler": {
        "interval": 30000,
        "size": 20
      },
      "pubsub": {
        "ignore": ["_peer-discovery._p2p._pubsub"],
        "init": [],
        "interval": 3000
      },
      "port": 50000,
      "debug": __PEER_DEBUG__
    }
