---
apiVersion: v1
kind: Secret
metadata:
  name: __NAMESPACE_NAME____INSTANCE_SUFFIX__-secret
  namespace: __NAMESPACE_NAME__
type: Opaque
stringData:
  acurast.proxy.config.json: |
    {
    "instanceName": "__NAMESPACE_NAME____INSTANCE_SUFFIX__",
    "permissions": {
      "allowList": [],
      "denyList": []
    },
    "bootstrap": {
      "peers": [ "__BOOTSTRAP_PEER__" ]
    },
    "peerId": {
      "id": "__PEER_ID__",
      "privKey": "__PEER_PRIVATE_KEY__",
      "pubKey": "__PEER_PUBLIC_KEY__"
    },
    "port": 50000,
    "schedulerTimeframe": 60000,
    "debug": __PEER_DEBUG__
    }
