---
apiVersion: v1
kind: Service
metadata:
  name: __NAMESPACE_NAME____INSTANCE_SUFFIX__-service
  namespace: __NAMESPACE_NAME__
spec:
  ports:
    - port: 9001
      targetPort: 9001
      protocol: TCP
      name: ws-port
    - port: 50000
      targetPort: 50000
      protocol: TCP
      name: p2p-port
  externalTrafficPolicy: Local
  type: ClusterIP
  selector:
    app: __NAMESPACE_NAME____INSTANCE_SUFFIX__
