---
apiVersion: v1
kind: Service
metadata:
  name: __NAMESPACE_NAME__-service
  namespace: __NAMESPACE_NAME__
spec:
  ports:
    - port: 9001
      targetPort: 9001
      protocol: TCP
  type: ClusterIP
  selector:
    app: __NAMESPACE_NAME__
