---
- name: Nginx setup
  hosts:
    - all
  tasks:
    - name: Copy files for nginx
      tags:
        - initial
        - update
      ansible.builtin.copy:
        src: nginx_letsencrypt/
        dest: /root/nginx_certbot/
        mode: '0774'
    - name: Create data directories
      ansible.builtin.file:
        path: /root/nginx_certbot/data/nginx
        state: directory
        recurse: true

    - name: Start nginx
      tags:
        - initial
      changed_when: true
      ansible.builtin.command:
        chdir: /root/nginx_certbot
        cmd: docker compose up -d

    - name: Restart nginx
      tags:
        - update
      changed_when: true
      ansible.builtin.command:
        chdir: /root/nginx_certbot
        cmd: docker compose restart

    - name: Wait for nginx being up (serving acme challenges!)
      ansible.builtin.wait_for:
        port: 80
        delay: 5

    - name: Get nginx-cert ws instance
      changed_when: true
      tags:
        - initial
      ansible.builtin.shell:
        chdir: /root/nginx_certbot
        cmd: ./init-letsencrypt.sh {{ instance_name | default('ws-1') }}.{{ server_name }}.acurast.com Y
        executable: /bin/bash

    - name: Restart nginx
      tags:
        - update
      changed_when: true
      ansible.builtin.command:
        chdir: /root/nginx_certbot
        cmd: docker compose restart nginx

    - name: Add ws1 conf
      tags:
        - initial
        - update
      ansible.builtin.template:
        src: ws-service.conf
        dest: /root/nginx_certbot/data/nginx/ws-service.conf
        mode: '0777'

    - name: Restart nginx
      tags:
        - update
      changed_when: true
      ansible.builtin.command:
        chdir: /root/nginx_certbot
        cmd: docker compose restart nginx
