---
version: '3'
services:
  proxy:
    restart: always
    build:
      context: ../websocket_proxy
    ports:
      - "50000:50000"
      - "9001:9001"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes: 
      - ./websocket-config.json:/usr/src/app/src/acurast.proxy.config.json
