---
version: '3'
services:
  nginx:
    restart: always
    image: nginx:1.25.1-alpine
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - "80:80"
      - "443:443"
      - "8448:8448"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  certbot:
    image: certbot/certbot:v2.6.0
    restart: always
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    logging:
      options:
        max-size: "10m"
        max-file: "3"
